name: Deploy on Pull Request

on: [pull_request]

jobs:
  deploy:
    name: deploy only if commit on pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Deploy on Pull Request
        uses: ./.github/actions/deploymentStaging
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
